name: CI

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
    - release/*

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build
      run: dotnet build -c Release
    - name: Test
      run: dotnet test -c Release
    - name: Pack
      if: github.event_name != 'pull_request'
      run: dotnet pack -c Release -o ./artifacts/NuGet
    - name: Artifacts
      if: github.event_name != 'pull_request' && matrix.os == 'windows-2019'
      uses: actions/upload-artifact@master
      with:
        name: NuGet
        path: ./artifacts/NuGet

  publish-windows:
    name: Publish windows-latest
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Publish
      if: github.event_name != 'pull_request'
      run: dotnet publish -c Release -f netcoreapp3.0 -r win7-x64 -o ./artifacts/Svg.Skia.Converter-netcoreapp3.0-win7-x64 ./src/Svg.Skia.Converter/Svg.Skia.Converter.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: Svg.Skia.Converter-netcoreapp3.0-win7-x64
        path: ./artifacts/Svg.Skia.Converter-netcoreapp3.0-win7-x64

  publish-ubuntu:
    name: Publish ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Publish
      if: github.event_name != 'pull_request'
      run: |
        dotnet publish -c Release -f netcoreapp3.0 -r debian.8-x64 -o ./artifacts/Svg.Skia.Converter-netcoreapp3.0-debian.8-x64 ./src/Svg.Skia.Converter/Svg.Skia.Converter.csproj
        dotnet publish -c Release -f netcoreapp3.0 -r ubuntu.14.04-x64 -o ./artifacts/Svg.Skia.Converter-netcoreapp3.0-ubuntu.14.04-x64 ./src/Svg.Skia.Converter/Svg.Skia.Converter.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: Svg.Skia.Converter-netcoreapp3.0-debian.8-x64
        path: ./artifacts/Svg.Skia.Converter-netcoreapp3.0-debian.8-x64
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: Svg.Skia.Converter-netcoreapp3.0-ubuntu.14.04-x64
        path: ./artifacts/Svg.Skia.Converter-netcoreapp3.0-ubuntu.14.04-x64

  publish-macOS:
    name: Publish macOS-latest
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Publish
      if: github.event_name != 'pull_request'
      run: dotnet publish -c Release -f netcoreapp3.0 -r osx.10.12-x64 -o ./artifacts/Svg.Skia.Converter-netcoreapp3.0-osx.10.12-x64 ./src/Svg.Skia.Converter/Svg.Skia.Converter.csproj
    - name: Artifacts
      if: github.event_name != 'pull_request'
      uses: actions/upload-artifact@master
      with:
        name: Svg.Skia.Converter-netcoreapp3.0-osx.10.12-x64
        path: ./artifacts/Svg.Skia.Converter-netcoreapp3.0-osx.10.12-x64
